import type { Metadata } from "next";
import { Poppins, Rubik_Wet_Paint } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--poppins",
});

const rubik = Rubik_Wet_Paint({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--rubik-wet-paint",
});

export const metadata: Metadata = {
  title: "Every Soul Will Taste Death",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${rubik.variable}`}>
        {children}
      </body>
    </html>
  );
}
